<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>FanslationStudio.Installer.App</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.22" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.22" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.22" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\FanslationStudio.png" LogicalName="FanslationStudio.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FanslationStudio.Installer.Core\FanslationStudio.Installer.Core.csproj" />
  </ItemGroup>

</Project>
