<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>FanslationStudio.LlmKit</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="BaseFiles\ChineseGlossary\*.yaml" />

    <EmbeddedResource Include="BaseFiles\Qwen25\Config.yaml" />
    <EmbeddedResource Include="BaseFiles\Qwen25\Prompts\*.txt" />
    <EmbeddedResource Include="BaseFiles\Qwen25\Corrections\*.txt" />
    <EmbeddedResource Include="BaseFiles\Qwen25\Dynamics\*.txt" />

    <EmbeddedResource Include="BaseFiles\Qwen35\Config.yaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
    <PackageReference Include="ToolGood.Words" Version="3.1.0.3" />
  </ItemGroup>

</Project>
